version: "3"

services:
  calendar-app:
    build: client/.
    ports:
      - 3000:3000
    environment:
      SERVER_URL: http://server:5005

  server:
    build: server/.
    ports:
      - 5005:5005
    environment:
      PORT: 5005
      MONGODB_NAME: sandbox-db
      MONGODB_COLLECTION_NAME: appointments
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
      - ./seed:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

volumes:
  mongo_data:
